### ISSUE TITLE
Ability to set device name/ID for TweetDraft?

### ISSUE THREAD

**Issue by nabijaczleweli** [QuietMisdreavus/twitter-rs#3]

**Comment by QuietMisdreavus** [comment]
I'm not sure what this request is for? Is it the `source` for the tweet (which is set by which consumer keys you use)? Supplemental information that wouldn't get sent with the tweet (which I'd prefer to keep out of the library if possible)? Something I haven't considered? Sorry if I'm being ill-spirited, but I don't have a lot of information to go on.

**Comment by nabijaczleweli** [comment]
You're goddamn right, why do I keep posting issues when I'm tired (he says while being tired)?

I meant something akin to the "via Twitter for Android" thing one sees when a tweet is twoten from the dedicated Android app, or is that just a specialcase of `source`?

**Comment by QuietMisdreavus** [comment]
Okay, yeah, that's just the `source` field. That's set based on what name you give to your app when you create it on https://apps.twitter.com. So for example, [this test post](https://twitter.com/QuietMisdreavus/status/771414872030674944), if loaded in a client that shows the source, would say something like "via QuietMisdreavus" because that's the name I gave to the app when I wanted some keys to mess around with. [This one](https://twitter.com/QuietMisdreavus/status/771414947557433344) would say "via TweetDeck" because that's where I posted that one. Same for "Twitter Web Client", "Twitter for Android", "Twitter for iOS", "Tweetbot for iOS", "Twidere", etc. That's not a field you can enter in directly.

**Comment by nabijaczleweli** [comment]
Oh, cool, I guess the web client just doesn't show that. Thanks!
