### ISSUE TITLE
Doc hosting options

### ISSUE THREAD

**Issue by adwhit** [QuietMisdreavus/twitter-rs#68]
I don't have access to @QuietMisdreavus site, so can't update the doc link.

But also, `docs.rs` is very decent these days, so I'm inclined to just use that as a host. We wouldn't be able to use it for the `master` branch, but that arguably isn't really necessary - if someone is using `master`, they can prob build their own. Thoughts?

**Comment by QuietMisdreavus** [comment]
Long-term, we should move to hosting the released docs on docs.rs. The use of my own hosting to host the docs is because egg-mode was originally created before docs.rs existed. Now that i'm not actively contributing to egg-mode, continuing to host the "canonical" docs on my site is a bottleneck. (And now that i'm a docs.rs contributor, i'm still managing the hosting, lol, but the docs will at least be automatically updated.)

As for the `master` docs, those were mainly for my own use as i was working on the library. I'm not sure of any other major use of them nowadays, so it's probably not a big deal to take those down.
