### ISSUE TITLE
The version of egg_mode on crates.io is out of date

### ISSUE THREAD

**Issue by jkarns275** [QuietMisdreavus/twitter-rs#7]
The last update on crates.io from November 30 2016; the library seems to have changed fairly significantly since then.

**Comment by QuietMisdreavus** [comment]
Yes, I have fallen quite behind in pushing updates. I'm currently wrapping up a documentation pass over the new DM Conversations struct/function, and a rewrite of the authentication docs. I don't expect it to be much longer, though; the docs pass is usually the last thing in the release process before I package it up.

**Comment by jkarns275** [comment]
Ah, I see. Perhaps you should mention that in the README for the time being, I was quite confused initially because of it :sweat_smile:

**Comment by QuietMisdreavus** [comment]
What should I mention? The README is currently up to date for the version on crates.io, and the changelog has the high-level overview of what's pending. The little note below the example code is a warning for the future version, which I guess could be misleading if you didn't know which version number was already on crates.io. I guess since the files in the examples/ directory are for the pending version, it could be an issue for someone trying to get into the library right now. I can add a link in the README to the repo as of the `v0.7.0` tag, so people can check the examples and implementation for that version.

**Comment by jkarns275** [comment]
This is what I had in mind but the edit you made also looks good. I didn't where to find the 0.7 doc before
```TOML
[dependencies]
# For the current release
egg-mode = "0.7.0"
# For the pending release
egg-mode = { git = "https://github.com/QuietMisdreavus/twitter-rs" }
```

**Comment by QuietMisdreavus** [comment]
Ah, yeah, I'd rather try not to have "use a git dependency" as an explicitly-mentioned option. People are totally welcome to if they know how, but I'd personally prefer it if they keep to the crates.io version if at all possible.

Also, there are two Documentation links at the top of the README, one to the crates.io version, and one for a "master or pretty close to it" version, so I can render and read documentation as I write it. The first "Documentation" link should still be the one for 0.7. If all else fails, there's also still [docs.rs](https://docs.rs/egg-mode/0.7.0/egg_mode/) in case you want an earlier version or just want to triple-check that my rendering is what you're using.
