### ISSUE TITLE
No support for lists

### ISSUE THREAD

**Issue by jkarns275** [QuietMisdreavus/twitter-rs#8]
I'd like to begin the process of adding support for lists. I've already added some (very basic) functionality. Should I continue?

**Comment by QuietMisdreavus** [comment]
I think this is wonderful! If you'd like to start adding lists support, I would love to see it.

I do have a couple style nits before you get too far in. One minor one is that your `decode_tweets`/`decode_users` functions already exist - there's a FromJson impl for `Vec<T>`, and it slots in neatly with the ones for Tweet and TwitterUser. You could use the `field` function from the `common::response` module (which is re-exported in `common`) to pull out the "users" field, if you need.

...in fact, now that I'm looking at `lists/members`, that's just a users cursor. You could make the `members` method return a CursorIter like some of the methods in the `user` module, and take out everything past the params handling.

As far as general structure, I feel like it would fit in with the rest of egg-mode more if these loader functions weren't methods from the List structure. I feel like List could fit well as a modified `tweet::Timeline`, but things like `members` would feel better as a bare function that just took the ListID as a parameter.

(Also, changing the `auth` re-export to a glob export actually exposes things like `get` and `post`, which I'd rather not be in the public API. That's fairly minor, though.)

-----

I feel like I've ragged on your code a lot, but I'm really excited that you wanted to help out! I say you should keep going! Even if we tweak the structure around some, it's still cool. I'm kinda opinionated about the overall design of egg-mode, so I apologize if I seem authoritarian about it. I can write up a CONTRIBUTING.md file with some tips, if you want. If you want to talk about it closer to real-time, I lurk on the Rust IRC as misdreavus, or you can poke me on Twitter, with the same username as on GitHub.

**Comment by jkarns275** [comment]
I certainly expected some criticism haha, I threw the code together quite quickly as I needed the functionality quickly 😅. I'll keep your style choices in mind.

**Comment by jkarns275** [comment]
@QuietMisdreavus If you wouldn't mind I'd like you to take a look at my fork, I think it's going in a direction you like but I'd like to make sure :smile:

**Comment by QuietMisdreavus** [comment]
Hey, sorry for not getting back to you!

You're on the right track, just have a couple structural things to point out. I see you've picked up on FromJson and the field method, so those will fit in a lot nicer now.

For `ListID`, you could probably collapse `SlugID` and `SlugName` into a single `Slug` variant that has the slug name and a `user::UserID` to represent either the ID or the screen name. I'm not too keen on the `from_*` methods, but it's harder to replace them with From impls like with `UserID`, so they can probably stay. You could probably hop over to `src/common/mod.rs` and add a `add_list_param` method to go alongside `add_name_param`. (Also, the match you have on `List::is_member` can be replaced with an `add_name_param` call. Another hidden gem of common. `>_>`)

A personal style I've taken so far is to have as many methods as I can be *only* bare functions, instead of making them associated methods of some struct. For example, I would personally take out `ListID::show` and move all that code into the bare `show` function you already have set up. Same for `List::members` and `List::is_member` - to fit in with the rest of the library, those should be lifted into those bare functions, which would just take a `ListID` and (for `is_member`) a `UserID`.

I'm not too keen on the `List` struct. Is it supposed to be an analogue to a `Timeline`? You might be able to just use `tweet::Timeline` wholesale, by just setting up the extra parameters you need and giving it the right link.

Also for `ListIter`, you could ditch most of that code by hopping over to `src/cursor.rs` and making a `ListCursor` that acts like the other cursors there. It looks like you should be able to use the existing `CursorIter` by plugging in a new `ListCursor` type like that. From what I can see in the four "call" methods you have there, their only difference is the link they call, so you can just hand that in at the very beginning to smash those functions together.

-----

Thanks so much for working on this! If you want, you can just submit the PR when you've got as many methods as you want down. I'm willing to just land this and mess around with it after the fact to get it in line with the rest of egg-mode. I admit my style can be a bit weird if you're not used to it, and you've done the hard work of just getting the code down in the first place.

**Comment by QuietMisdreavus** [comment]
I had a question about `member_of`, actually. Do you know what Twitter returns if the user isn't in the list? I'd like to avoid masking network errors and rate-limit information, if I can. This is going to be the "canonical" method for this endpoint, so I don't want to hide anything at that level.

**Comment by jkarns275** [comment]
In regards to member_of, I'm not entirely certain but from the looks of it, it will not return a user field if the user is not in the list. Similar methods in the api do that, but I couldn't find anything specifically saying what it returned online. 


As for your critiques, they all make sense. I was getting the minimal functionality I needed for a school project. If you want to grab the reigns from here feel free, I haven't added much else since my last commit

**Comment by QuietMisdreavus** [comment]
I've started bringing your work in under [a new branch](https://github.com/QuietMisdreavus/twitter-rs/tree/jkarns275-lists). Once I feel like it matches the rest of egg-mode, I'll merge it into master and it'll be official!

**Comment by QuietMisdreavus** [comment]
And now I've egg-mode-ified your List operations and merged it into master! Thanks for your work! It looks like since I didn't go through a formal pull request, it didn't put your name into the commit history, but I've made sure to mention you in the changelog.
